import { useEffect, useMemo, useState } from "react";
import UserPanel from "./UserPanel";
import AdminPanel from "./AdminPanel";
import AdminTicketPanel from "./AdminTicketPanel";
import { lotteryApi } from "./lotteryApi";
import { ArrowDown, ArrowRight, Check, Clock3, Dices, Menu, Minus, Moon, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Sun, Ticket, Trophy, X } from "lucide-react";

const numbers = ["019284","155090","228811","336729","403009","568956","709118","818284","927700","110011","290519","645192","081624","190745","224680","317459","420168","509327","630491","748205","871036","990261","012345","100001","123789","222908","316416","428997","517247","609112","734567","856140","945023","054321","162834","273945","384056","495167","506278","617389","728490","839501","940612","051723","163845","274956","385067","496178","507289","618390","729401","830512","941623","052734","164856","275967","386078","497189","508290","619401","720512","831623","942734","063845","174956","285067","396178","407289","518390","629401"];
const tickets = numbers.map((number, index) => ({ id: index + 1, number, price: [80, 100, 120, 100, 140, 100][index % 6], set: `ชุด ${String(index + 1).padStart(2, "0")}` }));
const baht = (value) => new Intl.NumberFormat("th-TH", { style: "currency", currency: "THB", minimumFractionDigits: 0 }).format(value);
const nextDraw = (now = new Date()) => {
  const candidates = [1, 16].map((day) => new Date(now.getFullYear(), now.getMonth(), day, 15, 0, 0));
  const upcoming = candidates.find((date) => date > now) || new Date(now.getFullYear(), now.getMonth() + 1, 1, 15, 0, 0);
  return { date: upcoming, label: new Intl.DateTimeFormat("th-TH", { day: "numeric", month: "short", year: "numeric" }).format(upcoming) };
};
const timeUntil = (target, now = new Date()) => {
  const totalSeconds = Math.max(0, Math.floor((target - now) / 1000));
  return { days: Math.floor(totalSeconds / 86400), hours: Math.floor((totalSeconds % 86400) / 3600), minutes: Math.floor((totalSeconds % 3600) / 60), seconds: totalSeconds % 60 };
};

function TicketCard({ ticket, onAdd, selected, drawLabel }) {
  return <article className="ticket-cut rounded-xl border border-slate-100 p-5 shadow-ticket transition hover:-translate-y-1 hover:shadow-xl">
    <div className="flex justify-between text-xs text-slate-500"><span>งวด {drawLabel}</span><span>{ticket.set}</span></div>
    <p className="my-5 font-['DM_Sans'] text-3xl font-bold tracking-[.18em] text-ink">{ticket.number}</p>
    <div className="flex items-center justify-between border-t border-dashed pt-4"><b className="font-['DM_Sans'] text-lg">{baht(ticket.price)}</b><button onClick={() => onAdd(ticket)} disabled={selected} className="grid h-9 w-9 place-items-center rounded-lg bg-amber-100 text-amber-800 transition hover:bg-gold disabled:cursor-default disabled:bg-slate-100 disabled:text-slate-400">{selected ? <Check size={18} /> : <Plus size={19} />}</button></div>
  </article>;
}

const thaiDate = (value) => new Intl.DateTimeFormat("th-TH", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));

function ResultsSection({ results }) {
  if (!results.length) return null;
  const [latest, ...previous] = results;
  return <section id="results" className="mx-auto max-w-6xl px-5 pb-20">
    <div className="mb-7 flex items-end justify-between gap-4">
      <div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-amber-700">ตรวจผลรางวัล</p><h2 className="text-3xl font-bold">ผลรางวัลย้อนหลัง</h2></div>
      <Trophy className="hidden text-amber-500 sm:block" size={28} />
    </div>
    <article className="overflow-hidden rounded-2xl bg-[#153f70] p-6 text-white shadow-[10px_10px_0_#f4dfb9] sm:p-8">
      <div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">งวดล่าสุด</p><h3 className="mt-2 text-2xl font-bold">{latest.label}</h3><p className="mt-1 text-sm text-blue-200">ประกาศผลเมื่อ {thaiDate(latest.drawDate)}</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-blue-100">รางวัลที่ 1</span></div>
      <div className="mt-7 rounded-xl bg-white/10 p-5"><p className="text-xs text-blue-200">เลขรางวัลที่ 1</p><p className="mt-2 font-['DM_Sans'] text-4xl font-bold tracking-[.18em] text-amber-300 sm:text-5xl">{latest.results?.firstPrize || "ยังไม่ประกาศ"}</p></div>
      {!!latest.results?.lastTwoDigits?.length && <div className="mt-5 flex flex-wrap items-center gap-3"><span className="text-sm text-blue-200">เลขท้าย 2 ตัว</span>{latest.results.lastTwoDigits.map((number) => <b key={number} className="rounded-lg bg-amber-300 px-4 py-2 font-['DM_Sans'] text-xl text-ink">{number}</b>)}</div>}
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-blue-200">เลขหน้า 3 ตัว</p><div className="mt-2 flex flex-wrap gap-2">{latest.results?.frontThreeDigits?.map((number) => <b key={number} className="rounded-lg bg-amber-300 px-3 py-2 font-['DM_Sans'] text-xl text-ink">{number}</b>)}</div></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-blue-200">เลขท้าย 3 ตัว</p><div className="mt-2 flex flex-wrap gap-2">{latest.results?.lastThreeDigits?.map((number) => <b key={number} className="rounded-lg bg-amber-300 px-3 py-2 font-['DM_Sans'] text-xl text-ink">{number}</b>)}</div></div></div>
    </article>
    {!!previous.length && <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{previous.map((draw) => <article key={draw._id} className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{thaiDate(draw.drawDate)}</p><h3 className="mt-1 font-bold text-ink">{draw.label}</h3></div><Trophy className="shrink-0 text-amber-500" size={19} /></div><div className="mt-5 border-t border-dashed pt-4"><p className="text-xs text-slate-500">รางวัลที่ 1</p><p className="mt-1 font-['DM_Sans'] text-2xl font-bold tracking-[.16em] text-ink">{draw.results?.firstPrize || "-"}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>เลขท้าย 2 ตัว</span>{draw.results?.lastTwoDigits?.map((number) => <b key={number} className="rounded bg-amber-100 px-2 py-1 font-['DM_Sans'] text-sm text-amber-800">{number}</b>)}<span className="ml-1">หน้า 3 ตัว</span>{draw.results?.frontThreeDigits?.map((number) => <b key={number} className="rounded bg-slate-100 px-2 py-1 font-['DM_Sans'] text-sm text-slate-700">{number}</b>)}<span className="ml-1">ท้าย 3 ตัว</span>{draw.results?.lastThreeDigits?.map((number) => <b key={number} className="rounded bg-slate-100 px-2 py-1 font-['DM_Sans'] text-sm text-slate-700">{number}</b>)}</div></div></article>)}</div>}
  </section>;
}

function Wheel({ onSearch, tickets: availableTickets }) {
  const [value, setValue] = useState("— — — — — —");
  const [angle, setAngle] = useState(0);
  const [spinning, setSpinning] = useState(false);
  const result = "";
  const spin = () => {
    if (!availableTickets.length) return;
    const next = availableTickets[Math.floor(Math.random() * availableTickets.length)].number;
    setSpinning(true);
    setValue("กำลังสุ่ม...");
    setAngle((old) => old + 1800 + Math.floor(Math.random() * 1440));
    setTimeout(() => { setValue(next.split("").join(" ")); setSpinning(false); }, 2700);
  };
  return <section className="mx-auto max-w-6xl px-5 pb-6"><div className="overflow-hidden rounded-2xl bg-gradient-to-br from-ink to-[#28619a] px-7 py-9 text-white sm:px-12"><div className="flex flex-col items-center justify-between gap-8 md:flex-row"><div className="max-w-lg"><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-amber-300">Lucky draw</p><h2 className="text-3xl font-bold">วงล้อสุ่มเลขนำโชค</h2><p className="mt-3 text-sm leading-7 text-blue-100">หมุนวงล้อเพื่อรับเลข 6 หลัก แล้วค้นหาสลากที่ตรงกับเลขนั้นได้ทันที</p><p className="my-5 font-['DM_Sans'] text-3xl font-bold tracking-[.2em] text-amber-300">{value}</p><div className="flex flex-wrap gap-3"><button onClick={spin} disabled={spinning} className="inline-flex items-center gap-2 rounded-lg bg-gold px-4 py-3 text-sm font-bold text-ink transition hover:bg-amber-300 disabled:opacity-70"><Dices size={17} />{spinning ? "กำลังหมุน..." : "หมุนวงล้อ"}</button><button onClick={() => value[0] !== "—" && onSearch(value.replaceAll(" ", ""))} disabled={value[0] === "—" || spinning} className="rounded-lg px-3 text-sm text-white disabled:opacity-40">ค้นหาเลขนี้ <ArrowRight size={15} className="inline" /></button></div></div><div className="relative h-52 w-52 shrink-0"><span className="absolute -top-2 left-1/2 z-10 -translate-x-1/2 text-xl text-amber-300">◆</span><div style={{ transform: `rotate(${angle}deg)` }} className="relative grid h-52 w-52 place-items-center rounded-full border-8 border-amber-300 bg-[conic-gradient(#e5a52e_0deg_36deg,#f9da8c_36deg_72deg,#e5a52e_72deg_108deg,#f9da8c_108deg_144deg,#e5a52e_144deg_180deg,#f9da8c_180deg_216deg,#e5a52e_216deg_252deg,#f9da8c_252deg_288deg,#e5a52e_288deg_324deg,#f9da8c_324deg)] transition-transform duration-[2700ms] [transition-timing-function:cubic-bezier(.12,.75,.15,1)]"><div className={`grid h-28 w-28 place-items-center rounded-full border-4 border-amber-100 bg-[#153f70] text-center font-['DM_Sans'] text-sm font-bold ${result ? "tracking-[.12em] text-amber-300" : "tracking-widest text-white"}`}>{result || <>LUCKY<br />SIX</>}</div></div></div></div></div></section>;
}

export default function App() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState(""); const [cart, setCart] = useState([]); const [inventory, setInventory] = useState(tickets); const [results, setResults] = useState([]); const [drawer, setDrawer] = useState(false); const [notice, setNotice] = useState(""); const [darkMode, setDarkMode] = useState(() => localStorage.getItem("lucky-six-theme") === "dark");
  const [now, setNow] = useState(() => new Date());
  const ownerKey = useMemo(() => { const saved = localStorage.getItem("lucky-six-cart-key"); if (saved) return saved; const next = crypto.randomUUID(); localStorage.setItem("lucky-six-cart-key", next); return next; }, []);
  useEffect(() => { document.documentElement.classList.toggle("dark", darkMode); localStorage.setItem("lucky-six-theme", darkMode ? "dark" : "light"); }, [darkMode]);
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { lotteryApi.tickets().then((data) => { const loaded = data.map((ticket) => ({ id: ticket._id, number: ticket.number, price: ticket.price, set: ticket.setCode || ticket.series || "สลากกินแบ่ง" })); if (!loaded.length) return; setInventory(loaded); return lotteryApi.cart(ownerKey).then((savedCart) => setCart(savedCart.items.map((item) => loaded.find((ticket) => ticket.id === item.ticketId) || ({ id: item.ticketId, number: item.number, price: item.priceSnapshot, set: "สลากกินแบ่ง" })))); }).catch(() => setNotice("ยังเชื่อมต่อ API ไม่ได้ จึงแสดงข้อมูลตัวอย่าง")); }, [ownerKey]);
  useEffect(() => { lotteryApi.results().then((data) => setResults(Array.isArray(data) ? data : [])).catch(() => setResults([])); }, []);
  const shown = useMemo(() => {
    if (filter === "0" || filter === "9") return inventory.filter((ticket) => ticket.number.endsWith(filter));
    if (filter === "11") return inventory.filter((ticket) => /(\d)\1/.test(ticket.number));
    return inventory.filter((ticket) => ticket.number.includes(query));
  }, [filter, inventory, query]);
  const isStoredTicket = (id) => /^[a-f\d]{24}$/i.test(String(id));
  const add = async (ticket) => {
    if (cart.some((item) => item.id === ticket.id)) return;
    try {
      // Initial sample tickets have numeric IDs. Send only MongoDB ticket IDs to the API.
      if (isStoredTicket(ticket.id)) await lotteryApi.addToCart(ownerKey, ticket.id);
      setCart((current) => [...current, ticket]);
      setNotice(`จองเลข ${ticket.number} แล้ว`);
      setTimeout(() => setNotice(""), 2200);
    } catch (error) { setNotice(error.message); }
  };
  const total = cart.reduce((sum, ticket) => sum + ticket.price, 0);
  const draw = nextDraw(now); const countdown = timeUntil(draw.date, now);
  const searchWheelResult = (number) => { setFilter(""); setQuery(number); };
  const filters = [{ label: "ทั้งหมด", value: "" }, { label: "เลขลงท้าย 0", value: "0" }, { label: "เลขลงท้าย 9", value: "9" }, { label: "เลขเบิ้ล", value: "11" }];
  return <><header className="sticky top-0 z-30 border-b border-stone-200/80 bg-cream/90 backdrop-blur"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5"><a href="#top" className="font-['DM_Sans'] text-xl font-semibold tracking-widest">✦ LUCKY <span className="text-amber-600">SIX</span></a><nav className="hidden gap-8 text-sm md:flex"><a href="#tickets">เลือกสลาก</a><a href="#how">วิธีสั่งซื้อ</a><a href="#results">ตรวจผลรางวัล</a></nav><div className="flex items-center gap-2"><button type="button" onClick={() => setDarkMode((current) => !current)} aria-label={darkMode ? "เปลี่ยนเป็นธีมสว่าง" : "เปลี่ยนเป็นธีมมืด"} title={darkMode ? "ธีมสว่าง" : "ธีมมืด"} className="grid h-10 w-10 place-items-center rounded-full border border-stone-300 bg-white text-ink transition hover:bg-amber-100">{darkMode ? <Sun size={17} /> : <Moon size={17} />}</button><button onClick={() => setDrawer(true)} className="flex items-center gap-2 rounded-full bg-ink px-4 py-2.5 text-sm text-white"><ShoppingBag size={16} />ตะกร้า <b className="rounded-full bg-gold px-1.5 text-ink">{cart.length}</b></button></div></div></header>
    <main id="top"><section className="hero-shell relative mx-auto flex max-w-7xl flex-col items-center justify-between gap-12 overflow-hidden px-5 py-18 md:flex-row md:py-24"><div className="relative z-10 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-amber-700">งวดถัดไป • {draw.label}</p><h1 className="font-['DM_Sans'] text-5xl font-bold leading-[.95] tracking-tight sm:text-7xl">เลขที่ใช่<br /><span className="text-amber-600">อาจเป็นของคุณ</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-600">เลือกสลากกินแบ่งรัฐบาลจากเลขที่คุณชอบ จองใส่ตะกร้า และจัดการประวัติคำสั่งซื้อได้ในที่เดียว</p><a href="#tickets" className="hero-cta mt-8 inline-flex items-center gap-5 rounded-lg bg-ink px-5 py-4 text-sm font-bold text-white shadow-lg shadow-slate-300/40 transition hover:-translate-y-0.5">เลือกเลขของคุณ <ArrowDown size={17} /></a><div className="mt-8 flex flex-wrap gap-5 text-xs text-slate-600"><span><Check className="mr-1 inline text-emerald-600" size={14} />คัดเลือกสลากจริง</span><span><ShieldCheck className="mr-1 inline text-emerald-600" size={14} />ชำระเงินปลอดภัย</span></div></div><aside className="hero-draw-card relative z-10 w-full max-w-sm rounded-2xl bg-[#153f70] p-8 text-white shadow-[16px_17px_0_#f4dfb9]"><div className="mb-8 flex items-center justify-between"><Sparkles className="text-amber-300" /><span className="rounded-full border border-blue-300/40 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-blue-100">Next draw</span></div><p className="text-xs text-blue-200">งวดประจำวันที่</p><h2 className="mt-1 text-3xl font-bold">{draw.label}</h2><hr className="my-6 border-blue-400/60" /><p className="text-xs text-blue-200">ปิดรับจองใน</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 font-['DM_Sans'] text-3xl font-bold"><span>{String(countdown.days).padStart(2, "0")}<small className="ml-1 text-xs font-normal text-blue-200">วัน</small></span><span>{String(countdown.hours).padStart(2, "0")}<small className="ml-1 text-xs font-normal text-blue-200">ชม.</small></span><span>{String(countdown.minutes).padStart(2, "0")}<small className="ml-1 text-xs font-normal text-blue-200">นาที</small></span><span>{String(countdown.seconds).padStart(2, "0")}<small className="ml-1 text-xs font-normal text-blue-200">วินาที</small></span></div><div className="mt-7 flex items-center gap-2 text-xs text-blue-100"><span className="h-2 w-2 rounded-full bg-emerald-400" />เปิดรับจองสลากอยู่</div></aside></section>
    <section className="grid grid-cols-3 border-y border-amber-200 bg-[#f8efd9] px-5 py-7 text-center"><div><b className="block font-['DM_Sans'] text-xl">6,000,000</b><span className="text-xs text-stone-600">บาท รางวัลที่ 1</span></div><div><b className="block font-['DM_Sans'] text-xl">80+</b><span className="text-xs text-stone-600">บาท ราคาเริ่มต้น</span></div><div><b className="block font-['DM_Sans'] text-xl">10 นาที</b><span className="text-xs text-stone-600">เวลาจองในตะกร้า</span></div></section><Wheel onSearch={searchWheelResult} tickets={inventory} />
    <section id="tickets" className="mx-auto max-w-6xl px-5 py-16"><div className="mb-7 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-amber-700">เลือกเลขนำโชค</p><h2 className="text-3xl font-bold">สลากพร้อมให้เลือก</h2></div><label className="flex w-full max-w-xs items-center gap-2 border-b border-ink pb-2"><Search size={17} /><input value={query} onChange={(event) => { setFilter(""); setQuery(event.target.value.replace(/\D/g, "")); }} maxLength="6" placeholder="ค้นหาเลขที่ชอบ" className="w-full bg-transparent text-sm outline-none" /></label></div><div className="mb-8 flex flex-wrap gap-2">{filters.map((item) => <button key={item.value} onClick={() => { setFilter(item.value); setQuery(item.value); }} className={`rounded-full border px-4 py-2 text-xs ${filter === item.value ? "border-ink bg-ink text-white" : "border-stone-300 text-slate-600"}`}>{item.label}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{shown.map((ticket) => <TicketCard key={ticket.id} ticket={ticket} drawLabel={draw.label} onAdd={add} selected={cart.some((item) => item.id === ticket.id)} />)}</div>{!shown.length && <p className="py-16 text-center text-slate-500">ไม่พบเลขที่ค้นหา ลองค้นหาตัวเลขอื่นดูนะ</p>}</section>
    <ResultsSection results={results} /><section id="how" className="mx-auto max-w-6xl px-5 pb-20"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-700">ง่ายใน 3 ขั้นตอน</p><h2 className="mt-2 text-3xl font-bold">เลือกเลขอย่างมั่นใจ</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[["01","เลือกเลขที่ชอบ","ค้นหาเลขมงคล หรือเลือกจากสลากที่พร้อมขาย"],["02","จองในตะกร้า","เลขของคุณจะถูกจองไว้ 10 นาที เพื่อให้ชำระได้ทัน"],["03","ชำระและรอลุ้น","เก็บประวัติสลาก พร้อมตรวจผลได้ในที่เดียว"]].map(([no,title,text]) => <article key={no} className="rounded-xl bg-slate-100 p-7"><b className="font-['DM_Sans'] text-amber-700">{no}</b><h3 className="mt-7 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section></main>
    <footer className="bg-ink px-5 py-10 text-blue-100"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-4 text-sm md:flex-row"><b className="font-['DM_Sans'] tracking-widest text-white">✦ LUCKY SIX</b><p>แพลตฟอร์มตัวอย่างสำหรับสลากกินแบ่งรัฐบาล</p><p className="max-w-sm text-xs">กรุณาตรวจสอบข้อกำหนดด้านอายุ ใบอนุญาต และกฎหมายที่เกี่ยวข้องก่อนใช้งานจริง</p></div></footer>
    {notice && <div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-lg bg-ink px-5 py-3 text-sm text-white shadow-xl">{notice}</div>}
    {drawer && <><button aria-label="ปิดตะกร้า" onClick={() => setDrawer(false)} className="fixed inset-0 z-40 cursor-default bg-slate-950/45" /><aside className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-700">รายการที่เลือก</p><h2 className="mt-1 text-2xl font-bold">ตะกร้าของคุณ</h2></div><button onClick={() => setDrawer(false)} className="grid h-9 w-9 place-items-center rounded-full bg-slate-100"><X size={19} /></button></div><div className="mt-6 rounded-lg bg-amber-50 p-3 text-xs text-amber-800"><Clock3 size={14} className="mr-1 inline" />เลขในตะกร้าจะถูกจองไว้ 10 นาที</div><div className="flex-1 overflow-auto">{cart.length ? cart.map((ticket) => <div key={ticket.id} className="flex items-center justify-between border-b py-5"><div><b className="font-['DM_Sans'] text-xl tracking-widest">{ticket.number}</b><span className="mt-1 block text-xs text-slate-500">งวด 16 ก.ย. 2569 · {ticket.set}</span></div><div className="text-right"><b>{baht(ticket.price)}</b><button onClick={() => setCart(cart.filter((item) => item.id !== ticket.id))} className="mt-1 block text-xs text-red-500">ลบ</button></div></div>) : <div className="grid h-full place-items-center text-center text-sm text-slate-500"><Ticket className="mx-auto mb-3 text-slate-300" size={35} />ยังไม่มีสลากในตะกร้า</div>}</div><div className="border-t pt-4"><div className="mb-4 flex justify-between"><span className="text-sm text-slate-500">ยอดรวม</span><b className="font-['DM_Sans'] text-2xl">{baht(total)}</b></div><button disabled={!cart.length} className="w-full rounded-lg bg-ink py-3.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">ดำเนินการชำระเงิน <ArrowRight size={16} className="ml-1 inline" /></button></div></aside></>}
    <UserPanel />
    <AdminPanel />
    <AdminTicketPanel />
  </>;
}
